### ISSUE TITLE
cobertura-2.1.1 throws InvocationTargetException worked in cobertura-1.9.4.1

### ISSUE THREAD

**Issue by sproket** [cobertura/cobertura#419]
Hi after attempting to upgrade to 2.1.1 I see this in my ant-task

Null Test: 	Caused an ERROR
null
java.lang.reflect.InvocationTargetException
Caused by: java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector

It happens on this line of my code

```
public abstract class BaseTest extends TestCase {

    **private static final Log log = Log.getLogger(BaseTest.class);**

```
