### ISSUE TITLE
100% of groovy/gradle unit tests fail after upgrading to Cobertura 2.1.1

### ISSUE THREAD

**Issue by samrocketman** [cobertura/cobertura#256]
This affects all latest major releases of Groovy between 1.8.9 and Groovy 2.4.3.

This is not an issue with the cobertura gradle plugin but likely with cobertura itself.  See issue stevesaliman/gradle-cobertura-plugin#81 for validation and verification of the issue.

When using Cobertura 2.0.3 100% of Jervis unit tests pass.  When using Cobertura 2.1.1 then all unit tests fail with the following error: `java.lang.NoClassDefFoundError...`.  See the failing build linked below for the full stack traces.

Additional resources

* [Failing build on all latest Groovy major releases between 1.8.9 and 2.4.3](https://travis-ci.org/samrocketman/jervis/builds/64361726)
* Commit that breaks the build: https://github.com/samrocketman/jervis/commit/2eb4dbaaf9a1b0e226a06bc5f6c92cd7cf402da3
* [Passing build after reverting the commit](https://travis-ci.org/samrocketman/jervis/builds/64497789)

Here's some feedback from @stevesaliman in issue stevesaliman/gradle-cobertura-plugin#81.

> I just tried to run the Jervis build with version 2.2.8 of the plugin. It fails if it uses Cobertura 2.1.1, but it succeeds if I change the Cobertura version to 2.0.3 (still using 2.2.8 of the plugin). I think this points to Cobertura itself as the source of the problem. I ran gradle dependencies under both configurations to see what classpath differences there are, and the one that jumps out to me is asm. Cobertura 2.0.3 used version 4, but Cobertura 2.1.1 uses version 5.
>
>You could try to exclude the asm dependency of cobertura itself and run with asm 4.1, but I think this issue should be reported in the cobertura project itself.
