### ISSUE TITLE
java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/LightClassmapListener

### ISSUE THREAD

**Issue by Mural2881** [cobertura/cobertura#423]
Hi there,

Currently cobertura 1.9.4.1 is configured in our Jenkin. Our application is running with Java 1.8 so some of the classes are not getting instrumented. So thought of upgrading to 2.1.1 version. 

I am getting the below error when upgrading cobertura to 2.1.1. 

java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/LightClassmapListener

We are using ANT 1.10.5 in our project. Any recommendation to resolve the issue will be helpful. 
Thank you
